### ISSUE TITLE
Cannot find .git folder

### ISSUE THREAD

**Issue by theblacklion** [akonwi/git-plus#149]
I usually have a project folder which contains several, sometimes nested, git repositories.
Now I open the project folder in Atom and try to view the log of the current file.
This does not work.
I would expect that it tries to traverse the path of the current file in order to find the correct .git folder, but it seems that it just tries to search it in the project folder.

I can understand that just querying the log of a repo without having it in the "root" or an open file is not possible, but if I have a file open, it should catch up this context and search from there.

Can you please fix this behaviour or tell me what I did wrong here. Thanks!

**Comment by akonwi** [comment]
The real bug here is that `Git init` should be the only available command in the command-palette since the project folder isn't a git repo.

This is an edge case I hadn't thought about before but it makes sense that the package should work this way. I'm considering this a new feature since it means being able to run any command for any repo file in the same project rather than one project per repo as we would generally use it.Creating new features isn't a priority right now but this will come second after fixing bugs. So unfortunately I can't promise this will be finished anytime soon but I will be working on implementing it.

Thanks for pointing this out. I can't believe I didn't think of this before

**Comment by theblacklion** [comment]
This is the way we're working here at the office. I just seem to be the first to try to use Atom for our projects :)
Wondering if I'm the only one using nested repos and stuff while being in Atom...

Would be really nice if you could at least make it possible so that I can blame or log a file in my situation.

Anyway.. nice work so far :)

**Comment by akonwi** [comment]
You're not the first to use nested repos in atom. If your project folder was a git repo and the children directories were submodules, then this would work just fine. Atom just assumes that the root folder is the project and it may or may not be a git repo and the package piggy backs off of that.

But I'll be working on this a bit over the weekend. 

And thank you. I'm glad you're enjoying it so far.

**Comment by akonwi** [comment]
I've published an update which should allow running all the commands for any repo in your project folder. You'll have to use the Git-plus palette instead of the default command palette though

**Comment by theblacklion** [comment]
It works somehow. But when I run status it gives me a list of changed files - which is nice - but then is missing the relative path into the repo in the path.

For example having this file tree:
root/
root/gitrepo/.git
root/gitrepo/readme.md
root/gitrepo/bla/bla/changedfile.php

Status then tries to open "bla/bla/changedfile.php" instead of "gitrepo/bla/bla/changedfile.php" and therefore Atom tries to generate an empty file in "root/bla/bla/changedfile.php".

**Comment by akonwi** [comment]
Give it a shot now. It should be addressed. It's working for me

**Comment by theblacklion** [comment]
Worked fine - thanks :).

Anything left you want to do or test here? Otherwise you can close this issue, I think...
