### ISSUE TITLE
What is the benefit from from passing the repo reference to the commands?

### ISSUE THREAD

**Issue by Azakur4** [akonwi/git-plus#185]
@akonwi I see in branch 1.0.0 u start pass the repo reference to the commands but the only use i see until now is that u use to get the repo path.

**Comment by akonwi** [comment]
Atom now allows opening multiple folders in one project. This is why atom is deprecating `project.getRepo()` in favor of `project.getRepositories()`. If a user has multiple git repos open in a project and they open the git-plus menu, while they aren't working on a file in either of those repos, then they are given the choice of which repo, they want to do these commands on. Once they make that selection, the commands in the menu use that selected repo to run the command.

Because there is the chance that someone is working with multiple repos in the same project, we can't simply rely on `atom.project.getRepositories()[0]` in every command. But if there is only one repo, then `git.getRepo()` will resolve to that. Also, if there is a file open, the package will try to return the repo that file belongs to if it is in a repo.
