### ISSUE TITLE
Location of commit pane

### ISSUE THREAD

**Issue by mwolfindale** [akonwi/git-plus#203]
The commit pane appears on the right (there used to be an option to move it to left, but didn't work).

When I do a quick `add` and `commit` the notification for the add gets in the way of the commit message.

Not a big deal but can be annoying - any chance we have the setting back to put the commit pane somewhere else (I'd prefer the bottom if possible, any from any notifications).

**Comment by akonwi** [comment]
Yea you know, the atom api for opening new files in split panes stopped working as expected a while ago and that's why it wasn't working to the left I think. And initially, the api allowed for opening files in any direction but then changed to just left and right.

Anyway, you can set the setting to right, down, up, or left now.
