### ISSUE TITLE
Improve notifications using the drawer

### ISSUE THREAD

**Issue by Gert-dev** [akonwi/git-plus#241]
Hello

I was wondering if there is a specific reason that git-plus uses Atom notifications for most of its messages but a bottom drawer specifically for push/pull? (This seems a tad inconsistent.) I was curious about this as, using [atom-notifier](https://atom.io/packages/atom-notifier), you can redirect most messages to your native desktop notifications, which is not possible for the bottom drawer notifications.

Thanks in advance

**Comment by akonwi** [comment]
Initially, I was just unsure of how to handle them because sometimes the message can be really wide because since they are intended for the command line and the bottom drawer resembles that better. I just don't think they fit well in the pop up notifications or even a native notification. But maybe a condensed + summarized version of the command can be put in an Atom notification

**Comment by akonwi** [comment]
Those are good observations and suggestions. I'm changing this issue title to better reflect what you've suggested. Hopefully I can work on it sometime or perhaps you or someone else will
