### ISSUE TITLE
keyboard shortcuts in status and stage files 

### ISSUE THREAD

**Issue by spencerlyon2** [akonwi/git-plus#281]
Is it possible to define keyboard shortcuts for the git status and git stage files views?

Specifically, what I would like to be able to do is the following (Note, following each suggestion I included a potential OSX keybinding -- I'm happy to define these myself in my keymap if the functions are exposed to atom):

in the status view:
- Stage a file (`cmd+s`)
- Unstage a file  (`cmd+u`)
- Go to a diff for the file under cursor (`cmd+d`) 
- Checkout a file to current branch (`cmd+delete` as in delete the local changes)

In the stage files view:
- View a diff of the (`cmd+d`)
- Activate the green "stage" button via the keyboard (`cmd+enter`)

I'm very sorry if this has already been discussed somewhere, but a search through the issues list didn't turn anything up for me.

**Comment by akonwi** [comment]
This hasn't been discussed specifically. I appreciate you looking to make sure though :+1:

But also those are very good ideas! As for the `cmd+enter` during file staging, that's been implemented as `shift-enter`. I would prefer using `cmd` instead of shift but I couldn't get it to work. That may be the case with the other commands too but I won't know until I try. 

I'm currently working on a major refactoring of the codebase right now so I'm holding off on new features. Check out #274 because I'd like to move to a view like that

**Comment by spencerlyon2** [comment]
Excellent.

I've used sublime-git extensively for a few years as well as magit (emacs inspiration for sublime git) and think that the status buffer is the way to go. If we do that _all_ of my concerns above will be addressed.

Also, another great feature of sublime-git is that in a diff view pressing `s` stages that hunk. Might be good inspiration for this package also.

**Comment by akonwi** [comment]
Closing this and marking as a duplicate. We'll keep #274 as the original. I'm about to start working on this finally
