### ISSUE TITLE
Git show remove extra {+ ... +}

### ISSUE THREAD

**Issue by doomstrike** [akonwi/git-plus#331]
If i do a git show HEAD~ in a terminal I would see something like this as an example:
```
+class BackupError(Exception):
+    pass
+
+
+class RestoreError(Exception):
+    pass
+
+
```
When using atom with gitplus and i do the same command the same lines are shown as:
```
{+class BackupError(Exception):+}
{+    pass+}


{+class RestoreError(Exception):+}
{+    pass+}
```
First issue is the square brackets around each line.
Second issue is the trailng + before the closing square bracket.
Third issue is that it doesn't show the 4 new lines above (2 lines after the pass). 

I'm used to working with the latter but not that I found atom and this amazing plugin I find it hard to look at code snippets cause the extra +} throws me off.

**Comment by akonwi** [comment]
The `{+` syntax highlights word diffs. You can turn that off in the package settings

**Comment by donmccurdy** [comment]
@akonwi which setting are you referring to? I think I am looking for an equivalent of `--word-diff=color` ideally.

Current:
<img width="459" alt="screen shot 2016-06-14 at 11 18 51 pm" src="https://cloud.githubusercontent.com/assets/1848368/16061706/68f1b680-3286-11e6-94e0-2266626899a3.png">

Preferred:
<img width="401" alt="screen shot 2016-06-14 at 11 19 05 pm" src="https://cloud.githubusercontent.com/assets/1848368/16061712/700aa8be-3286-11e6-8190-fdd60e3fea1a.png">

That's my preference but I understand your current default is better for a11y; would you accept a PR adding a dropdown options plain/none/color for the `--word-diff` parameter?

**Comment by akonwi** [comment]
The setting is the last option in the package settings. It's a check box labeled 'Word Diff'.

Pull requests are welcome. It may be difficult to achieve what you want because these commands are executed in a shell child process and the output is displayed in a file in atom. There is a syntax defined in atom to match on diff files and do the coloring. So the cli command that is run is `git diff --color=never [--word-diff]`. The color is disabled because the output will contain color codes for the terminal otherwise

**Comment by donmccurdy** [comment]
Oh, ok the 'Word Diff' option will be fine then thanks. :)

Hadn't realized the colors were defined by the syntax, maybe I'll try dialing back the colors on those brackets in my syntax highlighting instead.
