### ISSUE TITLE
Why do we get updates every 2 days without any changes?

### ISSUE THREAD

**Issue by karloluis** [akonwi/git-plus#357]
I keep getting update notifications on Atom and I came to check the changes. The past few commits make no changes at all. It gets quite annoying after a couple of weeks.

**Comment by jsg2021** [comment]
I'm sorry but this is kind of rude. 
@akonwi Is graciously developing this wonderful package free of charge.

Refactoring changes are still changes.

**Comment by akonwi** [comment]
@karloluis I have been thinking about this and I wish atom had a way to auto-update the packages on its own and unfortunately, I don't think that feature exists right now. There are bugs that only a handful of people experience and others that haven't been noticed yet so not every new update has changes that are relevant or obvious to every user. 

I try to resolve issues when I can in the little spare time I have because using atom isn't even in my daily routine. I work for a bank writing Java in intellij and use subversion so this is all completely out of my scope. I've created something that people enjoy using and I would hate to let them use this package painstakingly because no one has fixed a bug. 

A possible solution you can take right now is to not even update the package if you feel the changes are miniscule. One quick thing you can do is compare the package versions. If only the third number has changed, you can assume the update has minor changes and move on. You could go a step further and ignore any notice to update the package. 

I'm happy to know the package isn't giving you trouble otherwise

**Comment by karloluis** [comment]
I apologize for the confusion. I love this package as much as the next guy. I had to dig throw the commits to get better understanding of what was being changed, and surely enough there are a bunch of changes that went unnoticed for me.
