### ISSUE TITLE
add https password-base authentication support

### ISSUE THREAD

**Issue by gaydenko** [akonwi/git-plus#386]
Hi! I guess these issues 
- https://github.com/akonwi/git-plus/issues/368
- https://github.com/akonwi/git-plus/issues/373

(probably more, but these ones I have found at first) can be summarize as enhancement request to add password-base authentication support.

I'm the next forcing to switch to terminal for pushing :)

**Comment by bobum** [comment]
switching the remote from https to ssh did it or me - it was crated as https...needs to be SSH for git-plus

command looks like this:
`git remote set-url origin git@github.com:path/to/my/repo.git`

**Comment by gaydenko** [comment]
I guess, it is up to remote host system administrator to define possible transport/authentication ways. Forcing to use concrete scheme is both inconvenient and sometimes just impossible.

**Comment by akonwi** [comment]
@gaydenko There's a statement in the README about how this package is biased towards an ssh setup for remote repository interaction.

I am aware that this is a pain point for a lot of users but I haven't had a chance to work on it.

I'm closing this and referencing #336 because they are aiming for the same result
