### ISSUE TITLE
Toggle notifications with command and/or key binding.

### ISSUE THREAD

**Issue by garretwilson** [akonwi/git-plus#404]
Nice plugin! I was surprised, though, that I couldn't dismiss a push notification by hitting `Esc` (at least on Windows 10 Pro 64-bit). I searched the documentation and there doesn't seem to be a key binding or even a command for toggling the notification. How do I get rid of the notification without grabbing the mouse? Thanks.

**Comment by akonwi** [comment]
This used to be a functionality but it interfered with most usages of ESC. Someone else also attempted to re-introduce it but to no avail because trying to map a particular action to a globally common key like Escape won't work. There is a timeout setting in the package that you can change though. 

This isn't something I'm going to pursue anytime soon. If the notification isn't disappearing on its own then we have a problem. Otherwise the timeout setting is the only solution at this point.
