### ISSUE TITLE
Feature: Right Click on files/folders in tree

### ISSUE THREAD

**Issue by jcrowthe** [akonwi/git-plus#409]
I am wondering why right click functionality has not been added to this package yet? In other words, being able to right click on a file in the tree to select checkout, stash, add, etc.?

It seems like a trivial thing that would having to open the command palette, and type 'checkout cu' before "Checkout Current File" is selected, for example.

Is this something that you might consider adding?

**Comment by akonwi** [comment]
This is reasonable. I'm not opposed to the feature. I don't use the package that way that's why I didn't implement them initially. The two options in the context menu were submitted in pull requests. I'm going to lay a foundation for making more commands accessible in the context menus  so it's easier for contribution purposes and because I probably won't be able to sit down and port them all.

**Comment by akonwi** [comment]
The latest update includes 4 new commands which brings the total number of context menu options to 6. I've selected these commands because they are basic and common commands which can be run on single files or a directory
