### ISSUE TITLE
Git Push creates weird black bar with no feedback

### ISSUE THREAD

**Issue by jdsimcoe** [akonwi/git-plus#42]
So I used Git Push to push commits up to my repo. The command created a weird black bar at the bottom of the window and gave me no feedback that the push was successful:

![screenshot](http://cl.ly/image/2I0q0s3N0U0t/Image%202014-06-09%20at%2010.10.37%20AM.png)

Also, I found that the "Add All and Commit" overlay was dark and interfered with the status bar in my theme. Is there a way to perhaps use more native "styled" UI elements for this?

**Comment by hotoiledgoblinsack** [comment]
I've found that atom's behavior with my SSH keyring and public key authentication on Linux is wonky; sometimes when I start atom, I can't do any remote activity (such as pushing or pulling) without manually entering my password to unlock my private key. I have to do this each time. Other times this works fine (it seems to happen at random, but a reboot or log off is required to fix it).

It doesn't seem to be a system wide issue as whenever this happens, I can still open my terminal emulator outside of atom and push/pull just fine (and my SSH keyring is automatically unlocked as expected).

Other packages also seem to have trouble with this, as whenever this happens (the requesting of my passphrase) in git-plus, it also happens in other packages such as terminal emulator packages (inside atom, not outside as before). This is also the reason the black bar shows up for me; it means git's spawned SSH process is hanging on the background, waiting for a passphrase to be entered. Manually killing the SSH process effectively makes the black bar show git's output that pulling/pushing failed because authentication failed.
