### ISSUE TITLE
cannot commit

### ISSUE THREAD

**Issue by pratie** [akonwi/git-plus#425]
I'm on Windows 7, running latest atom and git plus. Whenever I try to commit I get the following message:
`fatal: could not read log file 'C:\repos\project01\.git\COMMIT_EDITMSG': No such file or directory`

If I have that directory open, I see the COMMIT_EDITMSG file being created, then it disappears and I get the error.

**Comment by hkinks** [comment]
Same issue here. (Windows 10)

**Comment by daniesteban** [comment]
+1 in Windows 7 wit Atom 1.7.3 and git-plus 5.13.4. I have the git binaries in Windows environment variables/path.
![error_commit](https://cloud.githubusercontent.com/assets/4419535/15017084/6f1f7804-1214-11e6-8eb7-dc83b79e3246.png)

**Comment by rickmed** [comment]
+1

**Comment by Harry-Harrison** [comment]
Also getting this 😞

**Comment by andrewmartin** [comment]
👍  here too

**Comment by lucacorti** [comment]
+1

**Comment by jonomacx** [comment]
+1

I have attempted this using Atom while opened as Administrator which does not work.

I have uninstalled git-plus completely and reinstalled but still experiencing this issue.

The folder described in the "fatal: could not read log file" does exist, and I can see the COMMIT_EDITMSG being created in the Atom file view side bar, and also in Windows Explorer. The issue occurs when I attempt to close and save the COMMIT_EDITMSG file which previously was initiating the commit ok.

Manually committing the file from the cmd line using GIT COMMIT works fine.

I've only recently started using Git so I'm still unsure of a lot of the commands, however the issue appeared to start when a local repo somehow appeared to exist instead of all commits going to my remote bitbucket repo. The commit process began to question which repo I wished to upload to. This dual repo listing appears to have gone away now, but now the Fatal error message is appearing always within Atom.

**Comment by akonwi** [comment]
@jonomacx I don't understand this part:

>I've only recently started using Git so I'm still unsure of a lot of the commands, however the issue appeared to start when a local repo somehow appeared to exist instead of all commits going to my remote bitbucket repo. The commit process began to question which repo I wished to upload to. This dual repo listing appears to have gone away now, but now the Fatal error message is appearing always within Atom.

If you have multiple remote destinations configured for the repository, then when you try to push you will be given the choice of where to push. If you're using the `Add all commit and push` option that sounds right to me. Is that what you're doing?

Unfortunately I can't replicate this and I don't have a windows machine to try it out on.

**Comment by jonomacx** [comment]
Hi @akonwi ,

The issue has been resolved for me by following your instructions on #224 

Thank you for your time investigating and for still working on the product!
