### ISSUE TITLE
Can't push new branches

### ISSUE THREAD

**Issue by chenasraf** [akonwi/git-plus#426]
Here's a scenario:
1. checkout development branch
2. checkout new branch -> give it a name
3. make changes
4. add all, commit and push
5. enter commit message and save
6. git-plus asks where to pull, since there's no remote branch yet, I select development to keep it up to date from base

Now what I expect to happen is:
1. pull from development
2. push into new branch

What actually happens:
1. pull from development
2. attempt to push but says "everything is up to date"

I then have to push my branch manually using `git push origin branch-name`

**Comment by binarious** [comment]
Same here. Any news?

**Comment by akonwi** [comment]
There's a new command that was introduced in the last week, `Push -u`, which will run git push with the `--set-upstream` flag.

Previously the push command would retry with the `--set-upstream` flag after an initial failure, which is not great because it sidesteps some pre-push hooks and you wouldn't know why the push failed initially. 

I think this should solve the problems you noted
