### ISSUE TITLE
No comment window pop up with commit, only notification window

### ISSUE THREAD

**Issue by XPLOT1ON** [akonwi/git-plus#491]
When I tried to commit after I made changes to two files, The commit message window did not pop up when I tried to commit. Instead a notification window came up, with message "nothing to commit". But, If i tried to "commit all", it works as expected where commit message window would appear and success notification message shows.

I have make sure that i am viewing the edited file (that I'm trying to commit) when i access the commit functionality

I am using Atom 1.8

**Comment by akonwi** [comment]
You need to make sure that you've staged the changed files to commit with the `Add` command or those like it otherwise when you try to commit, git isn't aware of which changes you want to commit.

The reason `Commit All` works is because it stages the files that have been changed automatically for you. This is very similar to using the `Add All And Commit` except it will only add the files that are already being tracked inside the repo. If you created a new file and used `Commit All` that new file would not be staged for the commit.
