### ISSUE TITLE
Incorrect tagging of added/removed when syntax highlighting is disabled

### ISSUE THREAD

**Issue by code-tree** [akonwi/git-plus#515]
Thanks for adding the option to disable syntax highlighting, but unfortunately lines are now being tagged incorrectly (e.g. as removed when actually were added).

![image](https://cloud.githubusercontent.com/assets/11289719/18620992/0562203e-7e47-11e6-8e07-237cf934d9ac.png)

**Comment by akonwi** [comment]
Including @sharedprophet since he has a lot of context on the new diff grammar.

It seems like the issue for @code-tree is that the '-' character in line 185 is being treated as an identifier for a removed line in the diff.

@Gert-dev I've opened a new issue for what you reported in https://github.com/akonwi/git-plus/issues/533

**Comment by sharedprophet** [comment]
I'll check it out soon. Can you save an example diff as a .diff file and attach it?

**Comment by sharedprophet** [comment]
In the meantime, have you tried enabling word diff?

**Comment by akonwi** [comment]
The fix for this will be included in the next version of the package
