### ISSUE TITLE
Exceptions when viewing diff's (repost of bug from atom/atom)

### ISSUE THREAD

**Issue by Gert-dev** [akonwi/git-plus#516]
Hello

It seems git-plus is causing some exceptions to be thrown since the new experimental syntax highlighting was added. The atom developers managed to reproduce and pin it down and requested that we post the issue here [1].

[1] https://github.com/atom/atom/issues/10350#issuecomment-248618306

**Comment by lednhatkhanh** [comment]
This is what happen when I use git plus diff

**Comment by akonwi** [comment]
@sharedprophet Looping you in here too. I guess the new grammar is producing unmatched close tags prematurely and illegally. This [comment](https://github.com/atom/atom/issues/10350#issuecomment-248618306) has an explanation. I think the atom api is becoming more fault tolerant so we can get away with this but I think it should be corrected if possible.

I need to admit I don't fully understand what is going on with the code for the diff grammar. Can you explain diff.js for me and/or point me to some resources?

**Comment by sharedprophet** [comment]
I'll investigate it as soon as I get a chance. Unfortunately there aren't a ton of good references for the way grammar stuff works; I was able to come up with this because of the work I did on the semanticolor package.

TextMate grammas: https://manual.macromates.com/en/language_grammars

If you have syntax highlighting off, the diff.json grammar is only used. That shouldn't give any errors because it works like any other Atom grammar.

The diff.js grammar is more tricky because it's trying to do things that are more tricky. It uses the diff.json grammar as a base but also attempts to parse the file for the extensions of the code files that changed, in order to load the applicable grammars for them and have those run on the code. Then it has to merge the two results together. Apparently there are edge cases I missed. Definitely something I want to get working properly.
