### ISSUE TITLE
Git difftool is now at the top of the right-click context menu within tree-view

### ISSUE THREAD

**Issue by intellix** [akonwi/git-plus#521]
It seems some version added `Git difftool` to the top of the right-click context menu within the tree-view (where Search in Directory used to be). It sounds a little petty, but it's annoying that something I barely use is quicker to access than Search. Feel like this item should be at the bottom of the context-menu.

Screenshot: https://www.dropbox.com/s/tpqy9shsletptal/Screenshot%202016-10-05%2012.05.19.png?dl=0

**Comment by Horta** [comment]
Exactly. It messes with our old brains. There are other packages also doing that, simply inserting more and more items in that menu. I get confused all the time.

**Comment by akonwi** [comment]
Sorry guys, I don't think I have control over the order of options in the context menu. It seems other package's menu items get put on the top of those from the tree-view package because I sometimes see other options that appear on top of the git-plus ones.

That context menu is dynamic and the contents are based on which item you're focused on and which packages you have installed. 

I'm adding separators so the git options are more clearly delineated but I can't do more than that
