### ISSUE TITLE
[QUESTION] UNC path error in CMD.exe

### ISSUE THREAD

**Issue by eirannejad** [akonwi/git-plus#539]
When project folder or remote repository is located on a network server (folder is mapped to a local drive), cmd.exe errors on UNC path. can not resolve UNC links.

**Comment by icimasa** [comment]
I have the same issue, trying to map to a network drive and also add network drive, but both result in UNC path not supported! CMD error

**Comment by akonwi** [comment]
Unfortunately, I don't have the means to troubleshoot and try to replicate this on a windows machine. Can you post more details about which commands you're running?

**Comment by eirannejad** [comment]
I'm seeing this error on `Diff` and `Add & Commit`. Basically any command that needs to communicate with the network remote. Is there anyway to put your package in debug mode so I can send you a debug report?

**Comment by eirannejad** [comment]
Here is the error on `Diff`
![giterror](https://cloud.githubusercontent.com/assets/8197916/20357625/84708866-abdd-11e6-95c9-733941df95c0.png)

**Comment by akonwi** [comment]
@eirannejad which version of atom are you using?

A similar problem has been raised in https://github.com/atom/atom/issues/13104 about resolving network paths differently in version 1.11.2 of atom. The fix for that was released in 1.12.x. 

Can you verify if the new version of atom resolves this for you?

**Comment by eirannejad** [comment]
Resolved in 5.25.4
