### ISSUE TITLE
autocomplete issues, repos, usernames for commit messages

### ISSUE THREAD

**Issue by maxheld83** [akonwi/git-plus#54]
This might be a little beyond the plans for this package, but it would still be great to have. I love the cross referencing on github, but keeping issue numbers and strings in mind for commit msgs is a hassle.

I also posted [this](http://discuss.atom.io/t/package-for-github-username-issues-etc-autocompletion-needed/10197) over at the atom discussion.

**Comment by akonwi** [comment]
I'm going to close this because I don't think this is a feature that fits with the rest of what the package offers and it's a pretty old issue now.

This is a feature that could be in a dedicated package, as part of atom-core, or as part of the language-git package because that is where the syntax recognition for commit messages comes from.
