### ISSUE TITLE
[REQUEST] Allow Commit No. Series for Checkout

### ISSUE THREAD

**Issue by pingshunhuangalex** [akonwi/git-plus#562]
At the moment, `git plus: checkout` only gives me a list of names branches. Just wonder if it's possible to type in historical commit no. series, so users can quickly jump among various code versions. Thanks.

P.S. `git time-machine` does provide the request feature, but it only realises it on a file basis, instead of the entire commit version.

P.S.S. BTW, is it possible to have a merge and push option (as well as its shortcut) in `git plus`. I personally find it quite useful. Thanks again.

**Comment by akonwi** [comment]
This isn't a feature I would want in this package. At most it would be a really low priority. I think this is something that fits better in the time machine package. 

For the merge and push option: I don't want to introduce these combo commands anymore because they aren't always common for workflows. I want the commands to be the simple and common git commands we use at the command line. A feature I'm looking into introducing is for flexible customization which would include allowing users to specify their own commands and/or chaining existing commands together so you can have merge and push.
