### ISSUE TITLE
[QUESTION] Should I have to specify my repo every time I add, commit, or push?

### ISSUE THREAD

**Issue by timothymcmackin** [akonwi/git-plus#570]
Sorry if I'm missing something obvious here. I have git-plus 5.29.0 and git-diff 1.1.0 installed in Atom 1.12.7 on Windows 7. I cloned several repos via an external program (cygwin) and added each repo as a separate project folder in Atom. So I have several repos that are represented by project folders in Atom. (No funny business, just a one to one relationship between Git repos and Atom project folders.) I have set user.name and user.email for each repo and I can pull, add, commit, and push from the cygwin command line normally, without giving a password. If it matters, I am using GHE and an SSH key with no passphrase.

In Atom, when I make a change to a file in a project folder, the color of the file in the sidebar changes to show that it has been changed. I right-click on the project folder and click Git > add. The Atom command bar opens, asking "Which repo?" I select my repo and get a success message that says that Atom has added files. (I verified that this Add worked via cygwin.)

I make some more changes and click Git > add again. I'm asked for the name of the repo again.

Now I'm ready to commit. I right-click the project folder again and click Git > add + commit... and again  I'm asked for the name of the repo. 

Do I really have to select the repo every time I add or commit? Seems like git-plus would be able to tell what repo my changes are in. These are simple repos with only one upstream. They're not forks or anything like that.

(Also, please forgive me if I'm being daft, but there's no Pull command in the right-click menu. That's something that I use all the time in Git before I start a piece of work -- is it really not in the main options? Do people sync with some other means?)

**Comment by akonwi** [comment]
This is a good find. Thanks for opening this issue.

I'll explain how the package finds a repository you're working with. It uses atom's api to get the repositories open in the project and if you have a file open, it will query for the repo the file belongs to. If you have no files open and there is only one repo in the project, that gets used. If you have no files open and there are multiple, then you get prompted for which repository you are trying to work with because there is nothing to infer upon.

Those context-menu options are only a small subset of the commands available with this package and they are also recent introductions. The main source of options can be accessed with `ctrl-shift-h` if you're on windows. Right now, the context menu options aren't deriving the repository based on the file you selected and they are still relying on a file being open and active to get the repo. For this reason, you need to specify which repository you are trying to act on and that needs to be changed.

Until this gets fixed, your workarounds are to keep the file you're trying to work with open or use the command palette. I'll also add the pull option to the context menu. I don't really use that menu so I haven't invested a lot time adding options there and I'm trying to make it easy for users to open pull requests with options they would like there.

**Comment by timothymcmackin** [comment]
Great -- thanks for the explanation.

**Comment by akonwi** [comment]
Changes for this are in v6.0.0
