### ISSUE TITLE
git diff pane squashed

### ISSUE THREAD

**Issue by mezpahlan** [akonwi/git-plus#590]
I'm trying to view a diff of my modified file from within Atom using the git-plus package. The diff does appear but it is too small to be readable / useable. It seems to be limited to 7 characters width (see attached screenshot).

Steps to reproduce:

1. Make changes to file
2. Select git plus diff on file
3. Observe opened diff pane

Expected results:

Git plus diff pane is able to be viewed filling the available space available.

Actual result:

Git plus diff pane is squashed to 7 columns.

![atom-git-plus-diff-bug](https://cloud.githubusercontent.com/assets/4974178/21743828/47d1edfc-d502-11e6-8bd5-30affdc47f96.png)

**Comment by akonwi** [comment]
I was able to reproduce this by changing my preferred line length to 7 and enabling 'Soft Wrap' and 'Soft Wrap At Preferred Line Length' in the 'Word Diff Grammar' section of the package settings. 

I think if you have the line length preference set globally in editor settings then I think you need to override it in settings of this package

**Comment by mezpahlan** [comment]
Thanks @akonwi. Yes I had set a global line length that I had forgot about. Making the change in the git-plus package settings allowed me to view diffs again! 

Something interesting though, I tried to set the line length in git-plus package settings to be the same as my global settings (160) but it would not allow this. It seems that 159 and 161 are allowed. I physically can't enter 160 into the entry box. It clears my value and prints `Unscoped value: 160`. Is this the intended behaviour?

**Comment by akonwi** [comment]
The default values for those input fields in atom are shown as the placeholder text. So if your global setting is 160, that's why it's just showing 160 as placeholder text. The 'Unscoped` means it's coming from outside of the package I think.

**Comment by mezpahlan** [comment]
Sorry I don't think I explained my issue correctly. My global settings aren't being respected. git-plus is defaulting to 8 when I try and match the global settings in the package settings. 8 isn't a feasible line length and I don't know where that is coming from. 

I've made an animated gif it it helps?

![git-plus-issue-590](https://cloud.githubusercontent.com/assets/4974178/21827246/b9543476-d782-11e6-8c9b-062a1304f775.gif)


What I expect to happen is: 
- If a global setting has been set, then use it. 
- git-plus isn't respecting my global settings at the moment. 
- Otherwise use a sensible package default. I would argue that 8 is not a sensible default, perhaps 80? 
- In either case allow the user to override the global setting / package default with a package setting even if it is with the same value as the aforementioned settings / defaults. 
- At the moment I try and override the package setting with the value of the global setting and it doesn't allow me to do this. Instead it snaps back to the package default of 8, which is inappropriate to view diffs.

**Comment by akonwi** [comment]
That is odd.

The package doesn't have a default line length setup so that '8' may have come from your input accidentally at some point. When you cleared the field it defaulted to the global setting though so it's odd that the guide didn't move at that point. I would suggest leaving that field empty and re-opening the diff file to see if it resets the guide.

This package doesn't do anything with those particular configuration options. Those are generated by atom because the package provides the diff grammar. The Word Wrap package uses those config options on a per file basis.

I recreated the same scenario and it works as expected. I started with a 160 as the global value, then put 8 in the package config and cleared it out and it defaulted back to 160 and the guide moved accordingly.

**Comment by mezpahlan** [comment]
Thanks. Yes very frustrating. I still couldn't reproduce what you were seeing so I looking in my `config.cson` file I saw the following:

```
".diff":
  editor:
    preferredLineLength: 8
    softWrapAtPreferredLineLength: true
    tabLength: 4
```

I have no idea where this came from. I don't remember setting this and can't find a package that sets this either. Removing that block causes the git diff to respect my global settings. Is this something that git-plus set / used to set? If not, any idea where it came from? Many thanks for helping troubleshoot!

**Comment by akonwi** [comment]
This package provides the diff grammar BUT it does not provide any configurations for the grammar. Those settings for the grammar are generated by atom.

The default values for those configurations that atom creates are inherited from the global values.

The config.cson contains the user provided values that replace package or editor defaults. I'm not quite sure where that block you have is coming from because I don't have it. The key in my config is `".diff.source"` so i'm not sure why yours would be different. With that said, I changed mine from `".diff.source"` to just `".diff"` and I started seeing the behavior you showed in the gif. It seems like ".diff" overrides the global values as the default for the diff grammar. 

This means at some point, you probably mistyped 8 as the line length preference and then somehow, the config block for ".diff" you just shared, was created. And then when you entered "160" or cleared the field, atom saw that as the global default of 160 so that's what the "Unscoped value: 160" is. But the guide doesn't move and that's probably because the wrap guide package saw the new override for the diff grammar from your config.cson as 8 still.

This is a weird bug/mistake. I suspect you could recreate this with any grammar in atom if you copied the config block and removed the 'source' part from the key. This is probably a bug in atom's settings package or the Word Wrap package
