### ISSUE TITLE
[REQUEST] Rearrange stash commands

### ISSUE THREAD

**Issue by Gert-dev** [akonwi/git-plus#606]
Hello

I have a very minor - at least I hope - request: would it be possible to rearrange the stash commands in the command menu? The current ordering is the following:

```
Stash: Apply (Keep)
Stash: Apply (Pop)
Stash: Delete (Drop)
Stash: Save Changes
```

The desired order would be:

```
Stash: Save Changes
Stash: Apply (Pop)
Stash: Apply (Keep)
Stash: Delete (Drop)
```

My reasoning is that, when requiring stash functionality, I often find myself using the workflow `Stash: (Save Changes)` → `Stash: Apply (Pop)`. I do this by opening up the command menu, filtering by `stash`. I always have to stop myself from immediately confirming, as the first result is the apply command instead of the mentally expected save. Confirming by accident then sometimes interferes with my current outstanding changes by generating conflicts whilst I find myself outing a large *sigh* because I forgot to move the selection down ;-). If a save were to be confirmed by accident, it is never destructive and can be reverted more easily by popping.

So far my large explanation of a small modification. I would like to hear your opinion on this :-).

Thanks in advance

**Comment by akonwi** [comment]
I get your concern. The commands are alphabetically sorted though, so the only way to change the order would be to change the titles. 

The first alternative though is to search for 'save' instead of stash if that's what you're trying to get to.

There is another way you can sort hack around this and that's to create a custom command with a name that would come first as an alias for what you really want. If you want the command to be in the git-plus palette, then enable the [custom commands](https://github.com/akonwi/git-plus#experimental-features) in the package settings and put this in your init script:

``` coffeescript
atom.packages.onDidActivateInitialPackages (p) ->
  if gitPlus = atom.packages.getActivePackage('git-plus')?.mainModule.provideService()
    gitPlus.registerCommand 'atom-text-editor', 'some-id:whatever-name-you-want', ->
      atom.commands.dispatch(document.querySelector('atom-workspace'), 'git-plus:stash-save')
```

and if you want it to only show up in the default palette then 

``` coffeescript
atom.commands.add 'atom-workspace', 'some-id:whatever-name-you-want', ->
  atom.commands.dispatch(document.querySelector('atom-workspace'), 'git-plus:stash-save')
```

**Comment by Gert-dev** [comment]
Thanks for the thorough explanation. I always used "stash" as that's what the git command is called, but perhaps I can just get used to using save/pop/drop instead. Thanks!
