### ISSUE TITLE
[REQUEST] Better icon for git plus output console

### ISSUE THREAD

**Issue by schrej** [akonwi/git-plus#613]
The little pin icon in the bottom right is not obviously related to git-plus at all. If not hovered over out of interest one does not know what it does at all.

I would propose to replace it with another icon or just text to make it more meaningful.

The [fontawesome git icon](http://fontawesome.io/icon/git/) would be quite a good candidate, it is not included within atom though.

Replacing it with `git+` is also a good alternative in my opinion if including the whole fontawesome font is to much overhead:
![screenshot](https://cloud.githubusercontent.com/assets/1710904/22572457/7fc7a61e-e9a4-11e6-9132-701a5f597ee7.png)

**Comment by cbcoutinho** [comment]
I second this idea - I think it would be great to change the logo to `git+` instead of a pin as mentioned by @schrej.

Also, right now the little pin is always visible and doesn't seem to be related to version control. If the open file is not under version control, the pin just sits there. Is it possible to make it visible only when the file is in a version-controlled project? That, or maybe it goes from a darker less visible color to a more highlighted color?

**Comment by akonwi** [comment]
This is a good idea. I'll change it to 'git+'. I think with an icon that just says 'git' then it could be mistaken as something else. 

@cbcoutinho I'll also change it to only show the icon when the package is fully activated so it's only visible when a git repository is in the project.

**Comment by cbcoutinho** [comment]
Hey @akonwi, icon looks great,

Sorry to re-open the issue, but I don't think the package activation is working correctly, or at least how I expect it should:

- Removing all git projects from the tree view does not remove the git+ icon, requires atom restart
- Opening atom without any previous git projects has no git+ icon, but opening a project into the tree view, or any of its files, doesn't open up the git+ icon. Also the short cuts don't work - only `git init`. Also requires atom restart

I'm was envisioning the package being more dynamic, but all these restarts are unnecessary. I think it's an question of either/or, just keep it always present. That's better than having the restart atom to get the package to work.

If you want me to open a new issue, let me know

**Comment by akonwi** [comment]
I can remove the icon when projects are removed. I'm not sure that I can add the icon when a project is added though because I'm consuming the status-bar package's service to create the icon, so I'll need to figure out if it's possible to manually invoke the service consumption. And even if it is, I probably shouldn't do that because those API's change. 

Maybe I will just always leave the pin there and disable it when there isn't a git repository in the workspace.

If you open a blank atom workspace. No git commands will be available. If you add a project which is not a repository, the init command will be available in the regular command palette. Once you add a git repository, then all the git-plus commands will be activated.

**Comment by akonwi** [comment]
__Update__: I've managed to re-add the icon when repositories are introduced into the workspace

**Comment by cbcoutinho** [comment]
This works wonderfully @akonwi, really great stuff. I hope other users
enjoy it as well. Thanks for taking the time to do this!

Cheers,
C
