### ISSUE TITLE
[REQUEST] Experimental stage/unstage panel keyboard-accessible Apply

### ISSUE THREAD

**Issue by sentience** [akonwi/git-plus#640]
The beta stage/unstage panel is wonderful, but unless I’m mistaken you need to reach for the mouse to click Apply, which is the only step that requires mouse interaction to stage a set of files and then create a commit.

Would it be possible for (say) ⌘Enter (Ctrl-Enter on Windows) to click the Apply button when this panel is open? Alternatively, it would be nice to toggle the staged files with spacebar and then hit Enter to Apply.

**Comment by sentience** [comment]
I’ve discovered that Ctrl-Enter clicks the Apply button, which is 👍 

Suggest this shortcut be changed to Cmd-Enter on Mac to conform to that platform’s keyboard shortcut standards.

**Comment by akonwi** [comment]
You can either use `shift` or `ctrl` as a modifier. Making `cmd-enter` work is more difficult for some reason. Command-enter doesn't even register when I try to use it. I'd like to use command enter but I think we're where we are today because it hasn't worked previously (see [this comment](https://github.com/akonwi/git-plus/issues/281#issuecomment-139385293) from 2015)

To address your initial concern, I'll add documentation about the keys you can use to confirm/cancel on that view to the README in case that will help others in the future.
