### ISSUE TITLE
[QUESTION] open custom-command output in new tab or split-pane

### ISSUE THREAD

**Issue by pfaion** [akonwi/git-plus#659]
Hi! First: I love git-plus and use it a lot!

Recently I started using custom commands in my init.coffee to optimize my workflows. One command that I like to use is `git log --oneline --graph` to get a quick overview over the repos where I work in small groups. Unfortunately git plus shows the output of the custom commands only for 'x' seconds. Is there a way of e.g. opening a new tab or split-pane with the output, like in the builtin git-plus commands for **git log** or **git diff**? Just simple text directly from the output would be great already.

I never hacked around with atom before and am rather a beginner when it comes to JavaScript, so I don't even have a general idea of whether that is possible in the init.coffee or how difficult that would be to implement. Any comments on this are greatly appreciated.

**Comment by akonwi** [comment]
I'm glad you like the package!

The output view above the status bar can be toggled by clicking the 'git+' logo in the bottom right of the status bar. That way, you can keep it open and scroll through it. Perhaps it would be nice to be able to keep it open, because if a new command is invoked then that view will auto close again.

It is possible to take that output and open it in a new tab by chaining to the promise.

``` javascript
gitPlus.registerCommand('atom-text-editor', 'akonwi:log-graph', () => {
  gitPlus.getRepo().then(repo => gitPlus.run(repo, 'log --oneline --graph'))
  .then(log => {
    atom.workspace.open('~/foo').then(editor => editor.setText(log))
  })
})
```

That simply opens a new tab for a file and then pastes the content into the buffer. Right now, the output view will still appear when you do this, so I need to update the api to offer a chance to disable that.

The problem you'll see in the file content is that there are terminal color codes. The output view of this package converts that to html but into a file is another problem. A solution is to add `--no-color` to the log command but then the file won't have the highlighting you probably want. In order to get some sort of highlighting, you would need to create a new grammar to represent the log view.

So what you want is possible though it will take some work to make it as smooth as we'd probably want.

**Comment by pfaion** [comment]
Many thanks for your detailed reply. I am already quite happy with the possibility to open the output console from the atom status bar. The fact that it closes after issuing another command is a little bit annoying though. A couple of considerations that come to my mind:

* Opening and closing the output console from the standard menu would be great, so you don't need to touch your mouse there (;
* Having a setting for enabling/disabling the auto-closing would be great.
* Can you open the output console from the init-script? This way you could e.g. disable auto-closing and then open the console after some custom command.

I don't want to press you into anything (: If you think something like this would be a quick fix, I'd greatly appreciate it though. Should I maybe change the title into [REQUEST] ?

**Comment by akonwi** [comment]
I've just pushed an update v7.9.0 which takes advantage of atom v1.17.0 docks. The output view is now part of the dock. This means it won't be closed automatically and you now have three ways to toggle the dock, by clicking the 'git+' logo, clicking the dock toggle button, or using a keymapping.

I'll work on improvements to the custom commands API to allow control over how the dock is updated.

**Comment by pfaion** [comment]
This is great already. Thx!
