### ISSUE TITLE
Console stays open after push

### ISSUE THREAD

**Issue by jord-love** [akonwi/git-plus#675]
I'm using the latest Mac versions of Atom + GitPlus. Seems whenever I do an Add All + Commit + Push the console stays open when it previously closed automatically.

If I dismiss the window it won't show any future push notifications.

I imagine this is a simple fix on my end?

![screen shot 2017-05-26 at 10 39 59](https://cloud.githubusercontent.com/assets/26397968/26473473/b3cebf34-41ff-11e7-8f67-b6c6846e7c19.png)

**Comment by akonwi** [comment]
This is sort of in contradiction to #674. The dock is an interesting UX element that can't satisfy everyone. Since the dock is a space shared by other packages I'm not really keen on automatically popping it open or closing it all the time because everyone's preference is different. Some people want to keep it open because there is other stuff there they want to see and then others don't want it open all the time.

If this package was to provide a setting for this, it would have to be aware of what else is in the dock and/or potentially conflict with other package settings related to the dock. I'd like to keep things simple and not have to worry about these things.

The dock is intended to be manually toggled. This package only opens it for the first command invoked that needs it because the output view isn't created at startup.

I'm going to close this so the discussion can continue on #674.
