### ISSUE TITLE
Amend doesn't show the whole commit message if it contains a line begins with "  -"

### ISSUE THREAD

**Issue by minorblend** [akonwi/git-plus#681]
When `amend` command loads a previous commit message which contains a line beginning with "  -" - two spaces followed by a dash -, git-plus cannot restore the whole message. It can restore only parts till two lines before the line. for example, if a commit message is the following:
Thi is commit message

> Commit title
>
> body line 1
> body line 2
> &nbsp;&nbsp;&dash;body line 3
> body line 4

git-plus only shows the following when `amend`

> Commit title
>
> body line 1

**Comment by akonwi** [comment]
Oh wow this is unfortunate. To recreate the previous commit message, the package uses `git whatchanged -1 --name-status --format=%B`. In order to split out the file statuses to update them, each line is iterated and tested against a regex looking for a file status indicator like `M|A|D|R|C|U` and unfortunately, an empty space is also one of those file statuses. So `  -body line 3` is treated as a file line and the previous line is assumed to be the empty line before the file statuses, so it gets removed too.

This will require some rethinking
