### ISSUE TITLE
Uncaught TypeError: q.drain is not a function

### ISSUE THREAD

**Issue by RazielSystems** [akonwi/git-plus#682]
[Enter steps to reproduce:]

1. ... use module remote-sync
2. ...click right in folder proyect
3. ...remote-sync -> Upload Folder

**Atom**: 1.17.2 x64
**Electron**: 1.4.16
**OS**: "Manjaro Linux"
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 7.9.3

### Stack Trace

Uncaught TypeError: q.drain is not a function

```
At /home/soporte/.atom/packages/git-plus/node_modules/async/lib/async.js:909

TypeError: q.drain is not a function
    at /packages/git-plus/node_modules/async/lib/async.js:909:23
    at /packages/git-plus/node_modules/async/lib/async.js:44:16
    at /packages/git-plus/node_modules/fs-plus/lib/fs-plus.js:438:24
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -0:18.3.0 remote-sync:upload-folder (span.name.icon.icon-repo)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
composer 0.5.0 
git-plus 7.9.3 
php-composer-completion 0.3.4 
php-cs-fixer 4.1.0 
remote-sync 4.1.5 
```

**Comment by akonwi** [comment]
what is the remote-sync package? I don't understand what's happening here.

**Comment by dboune** [comment]
@akonwi: It is a package that allows SFTP upload/download/sync.

https://github.com/yongkangchen/remote-sync

**Comment by dboune** [comment]
Looking a bit more and found this yongkangchen/remote-sync/pull/402 which may be related.

**Comment by akonwi** [comment]
If this issue is happening while you use remote-sync, then it's more likely that it's an issue with that package. This package is in no way related to any of the remote-sync functionality. The stacktrace might include git-plus in it because both of these packages use fs-plus, which has the async module as a dependency and remote-sync might be using the same async module that was installed for git-plus.
