### ISSUE TITLE
[REQUEST] Provide an option to stash uncommitted files

### ISSUE THREAD

**Issue by cbovis** [akonwi/git-plus#683]
I often like to stash all of my files including uncommitted ones however git-plus doesn't support this as far as I can see so I end up jumping back into Tower. It would be great if there was a way of stashing uncommitted files alongside other changes (perhaps via a config setting).

**Comment by akonwi** [comment]
There are commands for stashing.

- `Stash: Apply (Pop)`
- `Stash: Apply (Keep)`
- `Stash: Save Changes`
- `Stash: Delete (Drop)`
- `Stash: Save Changes With Message`

**Comment by cbovis** [comment]
@akonwi presently none of those commands will stash new files though which is what I'm after.

**Comment by akonwi** [comment]
Oh you want to stash 'untracked' files. Git is unaware of new files until you tell it to track them. So you need to do `git add` in order for git to follow changes to the file and then when you stash, it will be included. I'm hesitant to include this as configuration option though because that's how git works and my goal for most of these commands is to be what you would type at the command line

**Comment by cbovis** [comment]
Yeh sorry I mean untracked files. I understand your concern about keeping things pure however I feel it would be a useful productivity enhancement.

Perhaps an additional command along the lines of "Add All Files & Stash" would be better? This would be similar to other commands like "Add All, Commit & Push". I'm happy to put together a PR for it.

**Comment by adampk90** [comment]
This would be a convenient feature. As of now, I have to hit my terminal and run stash with “—include-untracked”

**Comment by akonwi** [comment]
It's now possible to do this with a [custom command](https://github.com/akonwi/git-plus/wiki/Custom-Commands-Snippets)
