### ISSUE TITLE
Getting error when I attempt to commit any file from Atom -> Git Plus

### ISSUE THREAD

**Issue by Ketan-vora** [akonwi/git-plus#749]
**TypeError: Cannot read property ‘itemForURI’ of undefined**

Steps to reproduce:

1. Install Git Plus release 8 package in to Atom
2. Create any file and try to commit using Git Plus -> Commit command

**Comment by fredzannarbor** [comment]
me too

**Comment by buggsdummy** [comment]
+1

**Comment by kritzi** [comment]
+1

**Comment by fredzannarbor** [comment]
+1

**Comment by fredzannarbor** [comment]
https://codeburst.io/uncaught-typeerror-cannot-read-property-of-undefined-in-javascript-c81e00f4a5e3

**Comment by linehammer** [comment]
Uncaught TypeError: [Cannot read property of undefined](http://net-informations.com/js/iq/unerror.htm)  error occurs in Chrome Browser when you read a property or call a method on an undefined object . There are a few variations of this error depending on the property you are trying to access. Sometimes instead of undefined it will say null.

**Comment by akonwi** [comment]
Is this still an issue for anyone?
