### ISSUE TITLE
[ISSUE] Output view broken -- no longer showing results clearly

### ISSUE THREAD

**Issue by brycefranzen** [akonwi/git-plus#758]
Output panel used to show most recent git command and result of the command. In the last couple of weeks something changed-- the output panel now stacks all git commands, and collapses each one so the results are not visible unless you click on the [•••] button to the left of the repo name.

Steps to reproduce:

1. git pull (panel no longer automatically opens -- even though config is enabled to do so)
2. manually open git+ panel
3. shows `[•••] [repoName] pull`
4. You have to click `[•••]` to view the results.

PLEASE FIX. THIS IS AN ISSUE!  It used to work. Now I cannot see the result of the command I run unless I scroll down the stack of all git commands and expand the most recent (which is at the bottom).

**Comment by akonwi** [comment]
This is all part of the last update. 

Your first step is definitely a bug because the panel should open automatically if that config is enabled. Also the the list is supposed to autoscroll and bring the latest event into view. 

For the fourth step, that's intentional right now. the next iteration on this new view will automatically expand the output of the latest event.

Would you prefer to see the the list of events in reverse order with the most recent at the top?

**Comment by brycefranzen** [comment]
Yeah, most recent always at the top and expanded. The rest can be collapsed. But definitely should autoReveal always.
  
  
  

  
  
  
  
  
>

**Comment by ashthespy** [comment]
A bit OT, but is it still possible to enable toast message when there is an error?

**Comment by akonwi** [comment]
version 8.2.0 has been updated to show most recent commands at the top and auto expand the latest if that config is enabled
