### ISSUE TITLE
[REQUEST] - Name of the theme / syntax theme in the Gif

### ISSUE THREAD

**Issue by LiamWinterton** [akonwi/git-plus#788]
Sorry to waste a github issue on this but I didn't know where else to ask.

Dying to know what that theme is!

**Comment by akonwi** [comment]
Wow it's been 5 years since that gif haha. The syntax theme is [one I created](https://atom.io/themes/dark-pastel-eighties-syntax) and haven't used/updated in a while but I do miss using it. The ui theme is linked there but it's [spacegray-eighties-ui](https://atom.io/packages/spacegray-eighties-ui). I'm not sure if either of those will still apply well with the latest versions of atom.
