### ISSUE TITLE
Doesn't delete the index.lock file

### ISSUE THREAD

**Issue by tusharmath** [akonwi/git-plus#97]
After the git commit in my system git/index.lock doesn't get deleted on its own.

**Comment by tylerFowler** [comment]
I do get this quite often.. After committing/pushing at least once in the same session and then trying to add all & commit (`cmd+shift+a a`) I will often, but not always, get an error message saying something like:

`Git 'index.lock' exists ...`

And then all I have to do is enter the shortcut again and it will work. Though it's odd because in the same situation when I do add all, commit & push (`cmd+shift+a p`) instead of giving me the error message it just won't do anything at all.

**Comment by pdaniell** [comment]
I am experiencing this issue quite frequently on Ubuntu Linux when I run "Add all commit and push". The difficulty  is that it is intermittent --- is it possible that there is a race condition? If the commit starts before the add command has finished, then the lock will still be there. But when I go to inspect the file system, there is never any index.lock file present. Also the state of the local git repository is always as though the add has succeeded but nothing else has happened.
